blank_issues_enabled: false
contact_links:
  - name: "ğŸ“– Read the README"
    url: https://github.com/keatre/whiskey-db#readme
    about: Make sure your issue isnâ€™t already explained in the documentation.
  - name: "ğŸ’¬ Discussions"
    url: https://github.com/keatre/whiskey-db/discussions
    about: For questions or general conversation.
